baseURL = "https://niranjanaambadi.github.io/learnings-site/"
relativeURLs = true
canonifyURLs = true
languageCode = "en-us"
title = "Learnings-Everything that matters"
theme = "PaperMod"
[params]
  description = "Research, machine learning, and writing"
  author = "Niranjana Ambadi"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  customCSS = ["css/custom.css"]
  math = true

[menu]
  [[menu.main]]
    name = "Writing"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[markup]
 [markup.highlight]
  style = "github-dark"
  lineNos = true
  codeFences = true
  guessSyntax = true
  noClasses = false
# Optional: taxonomies for tags/categories
[taxonomies]
  tag = "tags"
  category = "categories"
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML"]
