baseURL = "https://niranjanaambadi.com/"
languageCode = "en-us"
title = "Learnings-Everything that matters"
theme = "PaperMod"
[params]
  description = "Research, machine learning, and writing"
  author = "Niranjana Ambadi"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  customCSS = ["css/custom.css"]
  math = true

[menu]
  [[menu.main]]
    name = "Writing"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[markup]
  [markup.highlight]
    style = "github-dark"
    lineNos = true
    codeFences = true
    guessSyntax = true

  
